name: Rust Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions/setup-rust@v1
      with:
        profile: minimal

    - name: Build
      run: cargo build --release

    - name: Archive Release
      run: |
        mkdir release
        cp target/release/q_bot.exe release/
        cd release
        zip -r ../q_bot-windows-x64.zip *
        cd ..

    - name: Upload Release
      uses: actions/upload-artifact@v2
      with:
        name: q_bot-windows-x64
        path: q_bot-windows-x64.zip
