name: Rust

on:
  push:
    tags:
      - "v*"

jobs:
  
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --release

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          append_body: true
          files: target/release/q_bot.exe
          token: ${{ secrets.T }}
          tag_name: ${{ github.ref }}
          name: Q_Bot ${{ github.ref_name }}
          draft: false
          prerelease: false