name: Rust Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: 1.57.0

    - name: Build for Linux
      run: cargo build --release

    - name: Build for Windows
      run: cargo build --release --target x86_64-pc-windows-msvc

  release:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Upload Linux Release
      uses: actions/upload-artifact@v2
      with:
        name: q-bot-linux
        path: target/release/q_bot

    - name: Upload Windows Release
      uses: actions/upload-artifact@v2
      with:
        name: q-bot-windows
        path: target/release/q_bot.exe
