name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        toolchain: stable

    - name: Build for Linux
      run: cargo build --release

  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        toolchain: stable

    - name: Build for Windows
      run: cargo build --release

  publish:
    runs-on: ubuntu-latest
    needs: [build, build_windows]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Publish Linux executable
      run: |
        mkdir -p release
        cp target/release/q_bot release/q_bot_linux

    - name: Publish Windows executable
      run: |
        mkdir release
        copy target\release\q_bot.exe release\q_bot_windows

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: release
